#!/usr/bin/env python2.7

import sys
import os
if len(sys.argv) < 2:
	print "Expecting atleast one service-name"
	print "Usage: ./mystart <service-name> <service2-name> ..."
	sys.exit(0)

for i in range (1,len(sys.argv)):
	service= sys.argv[i]
	serviceConfig = service+".config.json" 
	serviceIds = service+".active_ids" 
	os.system('./start %s %s'%(serviceConfig, serviceIds))
